# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.network "public_network", bridge: "Virtual Switch"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "hyperv" do |hv|
    hv.enable_virtualization_extensions = true
    hv.linked_clone = true
    hv.maxmemory = 2048
  end
  config.vm.provision "ansible" do |ans|
    ans.playbook = "playbook.yml"
  end

  # Server 1
  config.vm.define "DebianVM_01" do |test|
    test.vm.hostname = "debianvm01.test"
  end

  # Server 2
  config.vm.define "DebianVM_02" do |test|
    test.vm.hostname = "debianvm02.test"
  end
end